Controllers/UserAuthController.cs
using JatraApplication.Models;
using JatraApplication.Models.DatabaseModels;
using JatraApplication.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JatraApplication.Controllers
{
    
    public class UserAuthController : Controller
    {
        const string SessionUser = "_Name";
        const string SessionUserId = "_Age";
        public IActionResult Index()
        {
            //HttpContext.Session.SetString(SessionUser,"");
            //HttpContext.Session.SetString(SessionUserId, "");
            return View();
        }
        [HttpPost]
        public JsonResult LogOn(string userName, string password)
         {

            Userrepo users = new Userrepo();

            var getUser = users.getUsername(userName);

            if (getUser != null)
            {
                var hashCode = getUser.VCode;
                var encodingPasswordString = LoginHelper.EncodePassword(password, hashCode);


                var data = users.ValidateUser(userName, encodingPasswordString);
                if (data == true)
                {
                    //HttpContext.Session.SetString(SessionUser, getUser.UserName.ToString());
                    //HttpContext.Session.SetString(SessionUserId, getUser.UserId.ToString());
                   
                    return Json(getUser.Id);
                }
                else
                {
                    var msg = ViewBag.ErrorMessage = "Invallid Password!!!";
                    return Json(msg);
                }
            }
            else
            {
                var msg = ViewBag.ErrorMessage = "Invallid User Name!! please Try again";
                return Json(msg);
            }

        }
        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public JsonResult SignUp(LoginModel users)
        {
            User entity = new User();
            Userrepo _userRepo = new Userrepo();

            var getUser = _userRepo.getUsername(users.UserName);
            if (getUser != null)
            {
                return Json("User is already registerd the email address:" + users.UserName);
            }

            try
            {

                var keyNew = LoginHelper.GeneratePassword(10);
                var password = LoginHelper.EncodePassword(users.Password, keyNew);
                _userRepo.VCode = keyNew;
                _userRepo.Password = password;
                _userRepo.Email = users.UserName;
                _userRepo.FirstName = users.FirstName;
                _userRepo.LastName = users.LastName;
                _userRepo.Roles = 1;
                int userId = _userRepo.AddUpdateUser();
                //HttpContext.Session.SetString(SessionUser, _userRepo.UserName);
                //HttpContext.Session.SetString(SessionUserId, userId.ToString());
                return Json(userId);
            }
            catch
            {
                return Json("Unable to register!!! Please Try Again");
            }
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Jatra</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />@*<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css" />*@

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet" />

    <!-- Custom styles for this template -->
    @*<link href="~/css/style.css" rel="stylesheet" />*@
    <!-- responsive style -->
    @*<link href="~/css/responsive.css" rel="stylesheet" />*@
    <style>


    </style>
</head>
<body>

    @{
        string currentUrl = Context.Request.Path.ToString().ToLower();
    }

    <div>
        <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    @*<img src="~/images/logo.png" alt="" />*@
                    <span>
                        Jatrai Jatra
                    </span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item @((currentUrl.Contains("home") || currentUrl == "/")? "active" : "")">
                            <a class="nav-link" href="/home">Home <span class="visually-hidden">(current)</span></a>
                        </li>
                        <li class="nav-item @((currentUrl.Contains("about"))? "active" : "")">
                            <a class="nav-link" href="about.html">About</a>
                        </li>
                        <li class="nav-item @((currentUrl.Contains("program"))? "active" : "")">
                            <a class="nav-link" href="program.html">Programs</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item @((currentUrl.Contains("userauth"))? "active" : "")">
                            <a class="nav-link" href="@Url.Action("Index", "UserAuth")">Login / Signup</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </div>



    <div class="m-1 p-1">
        <div>
            <div>
                <main role="main">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="card rounded-0 text-white bg-primary lg-12 fixed-bottom">
        <div class="card-body">

            <p class="card-text text-center">
                &copy;  2023 All Rights Reserved By- JatraApplications
            </p>
        </div>
    </footer>

    
    <!-- footer section -->
    <!-- Bottom Help Button-->
    @{
        Html.RenderPartial("~/Views/Common/Help.cshtml");
    }

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>


    @*<<<<<<< HEAD*@
    <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="~/js/bootstrap.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function openNav() {
            document.getElementById("myNav").style.width = "100%";
        }

        function closeNav() {
            document.getElementById("myNav").style.width = "0%";
        }
    </script>
    <script>

        $(document).ready(function () {
            $(".side-nav a").hover(function () {
                debugger
                var eventid = $(this).data("id");
                $("#calendardays #ev-" + eventid).css("background-color", "red");
                //$(this)
            }, function () { //this is for after the mouse is moved away
                var eventid = $(this).data("id");
                $("#calendardays #ev-" + eventid).css("background-color", "white");
                //$(this).css("background-color", "pink");
            });
        })
    </script>
</body>
</html>

Views/Shared/_SideBar.cshtml
@using JatraApplication.Models.DatabaseModels;
@{
    JatraDbContext _context = new JatraDbContext();
}
<div class="col-3 side-nav">
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" href="#">Events List</a>
        </li>
        @{

            foreach (var i in _context.Events.ToList())
            {
                <li class="nav-item">
                    <a class="nav-link" href="#">@i.EventName</a>
                </li>
            }
        }
    </ul>
</div>